resolver: lts-1.15

packages:
  - .

extra-deps:
  - conduit-1.1.7
  - connection-0.1.3.1
  - http-client-0.3.8.2
  - http-client-tls-0.2.0.3
  - http-conduit-2.1.2.2
  - json-0.9.1
  - primitive-0.6.1.0
  - random-1.1
  - tls-1.1.5
  - tls-extra-0.6.6
  - urlencoded-0.4.1
  - vector-0.11.0.0
